name: CoolTech CMS Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [server-alpha-hyperion-organization]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Setup the Environment File
        run: |
          cp /home/portfolio/projects/cooltech-cms/api/main.env /home/portfolio/projects/cooltech-cms/api/server-files/.env

      - name: Install Required Modules
        run: |
          bun install

      - name: Build the Project
        run: |
          bun run build

      - name: Restart App
        run: |
          pm2 stop "CoolTech CMS Server"
          pm2 reset "CoolTech CMS Server"
          pm2 start "CoolTech CMS Server"

    #PM2 START COMMAND: pm2 start bun --name "CoolTech CMS Server" -- run start
